#!/bin/bash
### "Install" the dotfiles

## Symbolic links to ~ (${HOME})
# ln -s: symbolic link, -f: if the target file exists, unlink it, -v: verbose
## RUNCOM
ln -sfv ${PWD}/runcom/.bash_profile ~
ln -sfv ${PWD}/runcom/.inputrc ~
ln -sfv ${PWD}/runcom/.vimrc ~

## GIT
ln -sfv ${PWD}/git/.gitconfig ~
ln -sfv ${PWD}/git/.gitignore_global ~

##VIM
ln -sfv ${PWD}/vim/colors ~/.vim
