#!/bin/bash
### "Install" the dotfiles

## Symbolic links to ~ (${HOME})
# ln -s: symbolic link, -f: if the target file exists, unlink it, -v: verbose

ln -sfv ${PWD}/.bash_profile ~
ln -sfv ${PWD}/.bashrc ~
##ln -sfv ${PWD}/.inputrc ~
ln -sfv ${PWD}/.vimrc ~

ln -sfv ${PWD}/git/.gitconfig ~
ln -sfv ${PWD}/vim/ ~/.vim
